---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', 'Server_Inventory_Linux.csv') }}"
  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./iterate_csv.j2"
        dest: ".x.yml"
  run_once: true
